# vim:shiftwidth=2:

image: "ruby:2.7"

cache:
  paths:
    - vendor

variables:
  LANG: "en_US.UTF-8"

before_script:
  - ruby -v
  - gem install --quiet --no-document bundler
  - bundle config set deployment 'true'
  - bundler install --quiet -j $(nproc)

test:
  stage: test
  script:
    - bundle exec rake -t ci
  artifacts:
    expire_in: 7 days
    paths:
      - tmp/
    reports:
      junit: tmp/rspec.xml

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv tmp/coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - master
