# vim:shiftwidth=2:

image: "ruby:2.7"

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

cache:
  paths:
    - vendor

variables:
  LANG: "en_US.UTF-8"
  DS_DISABLE_DIND: "true"

test:
  stage: test
  script:
    - ruby -v
    - gem install --quiet --no-document bundler
    - bundle config set deployment 'true'
    - bundler install --quiet -j $(nproc)
    - bundle exec rake -t ci
  artifacts:
    expire_in: 7 days
    paths:
      - tmp/
    reports:
      junit: tmp/rspec.xml

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv tmp/coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - master
