# vim:shiftwidth=2:

image: "ruby:2.6"

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - gem install bundler
  - bundler install --quiet -j $(nproc) --path vendor

test:
  script:
    - bundle exec toys standard
    - bundle exec toys bundle audit
    - bundle exec toys bundle leak
    - bundle exec toys rubycritic
    - bundle exec toys spec
    - bundle exec toys spec xml

