# vim:shiftwidth=2:

image: "ruby:2.6"

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - export GEM_VENDOR_DIR="vendor/ruby/$(basename $(gem environment gemdir))"
  - gem install --no-user-install --install-dir "${GEM_VENDOR_DIR}" bundler
  - "${GEM_VENDOR_DIR}/bin/bundle" install -j $(nproc) --path vendor

standardrb rubocop:
  script:
    - bundler exec standardrb

rspec:
  script:
    - bundler exec rspec spec

fasterer:
  script:
    - bundle exec toys fasterer

standardrb:
  script:
    - bundle exec toys standard

bundle audit:
  script:
    - bundle exec toys bundle audit

bundle leak:
  script:
    - bundle exec toys bundle leak

rubycritic:
  script:
    - bundle exec toys rubycritic

rspec:
  script:
    - bundle exec toys spec

rspec xml:
  script:
    - bundle exec toys spec xml
