# vim:shiftwidth=2:

image: "ruby:2.6"

cache:
  paths:
    - vendor

variables:
  LANG: "en_US.UTF-8"

before_script:
  - ruby -v
  - gem install --no-document bundler
  - bundler install --deployment --quiet -j $(nproc)

test:
  stage: test
  script:
    - bundle exec rake -t ci
  artifacts:
    paths:
      - tmp/
    reports:
      junit: tmp/rspec.xml
