---
# vim:shiftwidth=2:

image: "ruby:2.7"

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

stages:
  - build
  - test
  - pages
  - deploy

cache:
  paths:
    - vendor

variables:
  DS_DISABLE_DIND: "true"
  LANG: "en_US.UTF-8"
  RUBYOPT: "-E UTF-8"
  SAST_DEFAULT_ANALYZERS: "bandit, gosec, spotbugs, flawfinder, phpcs-security-audit, security-code-scan, nodejs-scan, eslint, tslint, secrets, sobelow, pmd-apex, kubesec"
  SAST_DISABLE_DIND: "true"

test:
  stage: test
  script:
    - ruby -v
    - ruby -e "puts Encoding.default_external"
    - gem install --quiet --no-document bundler
    - bundle config set deployment 'true'
    - bundle config set jobs "$(nproc)"
    - bundler install --quiet
    - bundle exec rake -t ci
  artifacts:
    expire_in: 1 day
    paths:
      - tmp/
    reports:
      junit: tmp/rspec.xml

pages:
  stage: pages
  dependencies:
    - test
  script:
    - mkdir -p public
    - mv pages-coverage-index.html public/index.html
    - mv tmp/coverage/ public/coverage
    - mv tmp/rubycritic/ public/rubycritic
    - command -v gzip   && find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -print0 | xargs -0r gzip   -f -k ; true
    - command -v brotli && find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -print0 | xargs -0r brotli -f -k ; true
  artifacts:
    paths:
      - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
